### ISSUE TITLE
use develop branch

### ISSUE THREAD

**Issue by justaddcoffee** [deepakunni3/IDGKG-gen#14]
I've made some PRs based on `master` branch, but there is actually a `develop` branch (which is a little behind). 

Should I sync up `develop` with `master` then do future PRs on `develop`?

**Comment by pnrobinson** [comment]
yes, please! We should do all branches off develop and only merge to master when things are working etc!

**Comment by justaddcoffee** [comment]
Cool - will do!

**Comment by justaddcoffee** [comment]
Okay, I've merged `master` into `develop`, and resolved several merge conflicts in `prototype_parse.py`. All 4 ingests complete without issue now...
